In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
import warnings
warnings.filterwarnings('ignore')





In [7]:
ds = np.loadtxt("mytxt.txt")
#dataset.head()

copy = ds

print (ds)

[[ 1.00000e+00  1.56600e+03  5.76852e-02]
 [ 1.00000e+00  1.90700e+03 -3.47872e-01]
 [ 1.00000e+00  2.35500e+03  5.76956e-01]
 ...
 [ 6.60000e+02  3.39000e+02  3.20847e-02]
 [ 6.60000e+02  3.67000e+02  2.29607e-01]
 [ 6.60000e+02  4.28000e+02  1.60489e+00]]


In [8]:
N,M = ds.shape
shape = ds.shape
# print(shape)

tot = M * N
print("Total data set:",int(tot))
percentage = 0.20                                               # persentage of NAN im array

c = int(tot * percentage)
print("x percentage of total:", c)
ds.ravel()[np.random.choice(ds.size, c, replace=False)] = np.nan
print (ds)

Total data set: 30000
x percentage of total: 6000
[[1.00000e+00 1.56600e+03 5.76852e-02]
 [1.00000e+00 1.90700e+03         nan]
 [1.00000e+00 2.35500e+03         nan]
 ...
 [6.60000e+02 3.39000e+02 3.20847e-02]
 [6.60000e+02 3.67000e+02 2.29607e-01]
 [        nan 4.28000e+02         nan]]


In [9]:
xs, ys = ds.nonzero()
start = 0

for x, y in zip(xs, ys):
            # print (x)
            # print(y)
            if  np.isnan(ds[x,y]) != True:
                pass
            else:
                ds[x,y] = start


In [11]:
vector = start
print (vector)

tolerance = 1e-06
iteration = 200
learning_rate = 0.0000001
K = 2

for i in range(iteration):

    diff = -learning_rate * K(vector)

    if np.all(np.abs(diff) <= tolerance):

        break

    vector += diff



0


TypeError: 'int' object is not callable